### ISSUE TITLE
missing script: build-local

### ISSUE THREAD

**Issue by worldsoft** [werner-duvaud/openleaf-markdown-pdf#1]
When typing the command "npm run build-local" the error "missing script: build-local" appears. How can you fix this? Thank you

**Comment by werner-duvaud** [comment]
Hi thanks for the report,

```
npm install
ng serve
```
Should launch the front-end in local at http://localhost:4200 

Don't forget to launch the backend too.

**Comment by worldsoft** [comment]
thanks it worked
